### PR TITLE
vhost & sysfw: Mark BIOS regions as "vhost_ignore"

### LINKED ISSUE #233: Issue with hugepages and vhost-net
When running NEMU with `/dev/hugepages` as the backing file for the guest RAM, and by also enabling `vhost` to the `virtio-net` device causes the network to fail. I mean to say we get no connectivity from the guest, which is basically due to the (virtio/vhost)-net device not operating as expected.

The command to reproduce this issue is:
```bash
sudo -E $HOME/build-x86_64/x86_64-softmmu/qemu-system-x86_64 \
-machine virt,accel=kvm,kernel_irqchip \
-cpu host \
-smp 2,maxcpus=4 \
-m 512M \
-object memory-backend-file,id=mem,size=512M,mem-path=/dev/hugepages,share=on \
-numa node,memdev=mem \
-kernel $HOME/linux/arch/x86/boot/bzImage \
-append 'console=ttyS0 console=hvc0 iommu=false root=/dev/vda3 rw rootfstype=ext4 data=ordered rcupdate.rcu_expedited=1 tsc=reliable' \
-bios /home/sebastien/workloads/OVMF.fd \
-device virtio-serial-pci,id=serial0 -device virtio-blk-pci,drive=image \
-drive if=none,id=image,file=$HOME/clear-25090-kvm.img,format=raw \
-device virtconsole,chardev=charconsole0,id=console0 \
-chardev stdio,id=charconsole0 \
-netdev tap,ifname=tapunicorn0,id=network-0,vhost=on \
-device driver=virtio-net-pci,netdev=network-0,mac=02:42:ac:11:00:02
```
We get interesting logs:
```
qemu-system-x86_64: vhost_region_add_section:Section rounded to 0 prior to previous c0000
qemu-system-x86_64: vhost_region_add_section:Section rounded to 0 prior to previous c0000
qemu-system-x86_64: vhost_region_add_section:Section rounded to 0 prior to previous c0000
qemu-system-x86_64: vhost_region_add_section:Section rounded to 0 prior to previous c0000
qemu-system-x86_64: vhost_region_add_section:Section rounded to 0 prior to previous c0000
qemu-system-x86_64: vhost_region_add_section:Section rounded to 0 prior to previous c0000
qemu-system-x86_64: vhost_region_add_section:Section rounded to 0 prior to previous c0000
qemu-system-x86_64: vhost_region_add_section:Section rounded to 0 prior to previous c0000
qemu-system-x86_64: vhost_region_add_section:Section rounded to 0 prior to previous c0000
qemu-system-x86_64: vhost_region_add_section:Section rounded to 0 prior to previous c0000
qemu-system-x86_64: vhost_region_add_section:Section rounded to 0 prior to previous c0000
qemu-system-x86_64: vhost_region_add_section:Section rounded to 0 prior to previous c0000
qemu-system-x86_64: vhost_region_add_section:Section rounded to 0 prior to previous c0000
qemu-system-x86_64: vhost_region_add_section:Section rounded to 0 prior to previous c0000
qemu-system-x86_64: vhost_region_add_section:Section rounded to 0 prior to previous c0000
qemu-system-x86_64: vhost_region_add_section:Section rounded to 0 prior to previous c0000
qemu-system-x86_64: vhost_region_add_section:Section rounded to 0 prior to previous c0000
qemu-system-x86_64: -device virtio-serial-pci,id=serial0: vhost_region_add_section:Section rounded to 0 prior to previous c0000
qemu-system-x86_64: -device virtio-serial-pci,id=serial0: vhost_region_add_section:Section rounded to 0 prior to previous c0000
qemu-system-x86_64: -device virtio-serial-pci,id=serial0: vhost_region_add_section:Section rounded to 0 prior to previous c0000
qemu-system-x86_64: -device virtio-serial-pci,id=serial0: vhost_region_add_section:Section rounded to 0 prior to previous c0000
qemu-system-x86_64: -device virtio-serial-pci,id=serial0: vhost_region_add_section:Section rounded to 0 prior to previous c0000
qemu-system-x86_64: -device virtio-serial-pci,id=serial0: vhost_region_add_section:Section rounded to 0 prior to previous c0000
qemu-system-x86_64: -device virtio-blk-pci,drive=image: vhost_region_add_section:Section rounded to 0 prior to previous c0000
qemu-system-x86_64: -device virtio-blk-pci,drive=image: vhost_region_add_section:Section rounded to 0 prior to previous c0000
qemu-system-x86_64: -device virtio-blk-pci,drive=image: vhost_region_add_section:Section rounded to 0 prior to previous c0000
qemu-system-x86_64: -device virtio-blk-pci,drive=image: vhost_region_add_section:Section rounded to 0 prior to previous c0000
qemu-system-x86_64: -device virtio-blk-pci,drive=image: vhost_region_add_section:Section rounded to 0 prior to previous c0000
qemu-system-x86_64: -device virtio-blk-pci,drive=image: vhost_region_add_section:Section rounded to 0 prior to previous c0000
qemu-system-x86_64: -device driver=virtio-net-pci,netdev=network-0,mac=02:42:ac:11:00:02: vhost_region_add_section:Section rounded to 0 prior to previous c0000
qemu-system-x86_64: -device driver=virtio-net-pci,netdev=network-0,mac=02:42:ac:11:00:02: vhost_region_add_section:Section rounded to 0 prior to previous c0000
qemu-system-x86_64: -device driver=virtio-net-pci,netdev=network-0,mac=02:42:ac:11:00:02: vhost_region_add_section:Section rounded to 0 prior to previous c0000
qemu-system-x86_64: -device driver=virtio-net-pci,netdev=network-0,mac=02:42:ac:11:00:02: vhost_region_add_section:Section rounded to 0 prior to previous c0000
qemu-system-x86_64: -device driver=virtio-net-pci,netdev=network-0,mac=02:42:ac:11:00:02: vhost_region_add_section:Section rounded to 0 prior to previous c0000
qemu-system-x86_64: -device driver=virtio-net-pci,netdev=network-0,mac=02:42:ac:11:00:02: vhost_region_add_section:Section rounded to 0 prior to previous c0000
qemu-system-x86_64: vhost_region_add_section:Section rounded to 0 prior to previous c0000
qemu-system-x86_64: vhost_region_add_section:Section rounded to 0 prior to previous c0000
qemu-system-x86_64: vhost_region_add_section:Section rounded to 0 prior to previous c0000
```

One thing to notice is that this issue is tied to the usage of hugepages because if we replace `/dev/hugepages` with `/dev/shm`, we don't run into this issue anymore.
And at the same time, it seems related to `vhost-net` because if we remove `vhost=on` from the `virtio-net-pci` device in the command line, we don't get this issue either.

__Note:__ Make sure you have enough hugepages on your system by running `sudo sysctl vm.nr_hugepages=1024`.

### PR DESCRIPTION
**Pull request by rbradford**
Without this change vhost will try to use the memory regions created by
pc_system_rom_init() which have a page size that does not match the
system memory (they differ as the latter is backed by an fd which
determines the page size.)

The vhost code normally rejects BIOS regions as they are marked R/O
however we cannot do that with the virt platform as we lack a PAM to
have the regions remapped to R/W for some firmwares (i.e. Seabios) to
use whilst booting.

Instead workaround this issue by adding a member to the region to
indicate that vhost should ignore this region.

Fixes: #233

Signed-off-by: Rob Bradford <robert.bradford@intel.com>

### CODE REVIEW

File: hw/virtio/vhost.c [hunk 1]
```diff
@@ -392,7 +392,8 @@ static bool vhost_section(struct vhost_dev *dev, MemoryRegionSection *section)
     bool log_dirty = memory_region_get_dirty_log_mask(section->mr) &
                      ~(1 << DIRTY_MEMORY_MIGRATION);
     result = memory_region_is_ram(section->mr) &&
-        !memory_region_is_rom(section->mr);
+        !memory_region_is_rom(section->mr) &&
+        !section->mr->qvhost_ignore;
```
Comment (sboeuf) [inline hw/virtio/vhost.c]: s/qvhost_ignore/vhost_ignore/

**Review by sboeuf — APPROVED** [review]
